import { Document, Page, Text, View, Image, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import type { ReportResult } from '@/lib/reports/types';

const BRAND = '#00A6E0';
const DARK = '#061633';
const MUTED = '#6B7F9E';

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 9, fontFamily: 'Helvetica', color: '#111111' },
  header: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, borderBottomWidth: 2, borderBottomColor: BRAND, paddingBottom: 10 },
  logo: { width: 120 },
  headerText: { marginLeft: 12 },
  business: { fontSize: 13, fontWeight: 'bold', color: DARK },
  title: { fontSize: 11, fontWeight: 'bold', marginTop: 2 },
  meta: { fontSize: 8, color: MUTED, marginTop: 2 },
  tableHeader: { flexDirection: 'row', backgroundColor: BRAND, paddingVertical: 5, paddingHorizontal: 4 },
  tableHeaderCell: { color: '#FFFFFF', fontWeight: 'bold', fontSize: 8, flex: 1 },
  tableRow: { flexDirection: 'row', paddingVertical: 4, paddingHorizontal: 4, borderBottomWidth: 0.5, borderBottomColor: '#DDDDDD' },
  tableRowAlt: { backgroundColor: '#F2F7FB' },
  tableCell: { fontSize: 8, flex: 1 },
  right: { textAlign: 'right' },
  totalsRow: { flexDirection: 'row', paddingVertical: 5, paddingHorizontal: 4, borderTopWidth: 1, borderTopColor: DARK, marginTop: 2 },
  totalsCell: { fontSize: 8, fontWeight: 'bold', flex: 1 },
  footer: { position: 'absolute', bottom: 20, left: 32, right: 32, flexDirection: 'row', justifyContent: 'space-between', fontSize: 7, color: MUTED },
});

function cellText(kind: string, value: string | number | null): string {
  if (value === null || value === undefined || value === '') return '—';
  if (kind === 'money') {
    const n = Number(value);
    const formatted = Math.abs(n).toLocaleString('en-ZM', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    return n < 0 ? `-K ${formatted}` : `K ${formatted}`;
  }
  return String(value);
}

export interface ReportDocProps {
  result: ReportResult;
  logoDataUri: string | null;
  systemName: string;
}

/** Render the report PDF to a Buffer (call from API routes, not client code). */
export async function renderReportPdf(props: ReportDocProps): Promise<Buffer> {
  return renderToBuffer(<ReportDoc {...props} />);
}

export function ReportDoc({ result, logoDataUri, systemName }: ReportDocProps) {
  const { meta, columns, rows, totals } = result;
  return (
    <Document>
      <Page size="A4" orientation="landscape" style={styles.page}>
        <View style={styles.header} fixed>
          {logoDataUri ? (
            // eslint-disable-next-line jsx-a11y/alt-text
            <Image src={logoDataUri} style={styles.logo} />
          ) : null}
          <View style={styles.headerText}>
            <Text style={styles.business}>{meta.businessName}</Text>
            <Text style={styles.title}>{meta.title}</Text>
            <Text style={styles.meta}>
              Period: {meta.from} to {meta.to} • Generated by {meta.generatedBy} on {meta.generatedAt.split('T')[0]}
            </Text>
          </View>
        </View>

        <View style={styles.tableHeader}>
          {columns.map((c) => (
            <Text key={c.key} style={[styles.tableHeaderCell, (c.kind === 'money' || c.kind === 'number') ? styles.right : undefined]}>
              {c.label}
            </Text>
          ))}
        </View>

        {rows.map((r, i) => (
          <View key={i} style={[styles.tableRow, i % 2 === 1 ? styles.tableRowAlt : undefined]} wrap={false}>
            {columns.map((c) => (
              <Text key={c.key} style={[styles.tableCell, (c.kind === 'money' || c.kind === 'number') ? styles.right : undefined]}>
                {cellText(c.kind, r[c.key] ?? null)}
              </Text>
            ))}
          </View>
        ))}

        {totals ? (
          <View style={styles.totalsRow}>
            {columns.map((c) => (
              <Text key={c.key} style={[styles.totalsCell, (c.kind === 'money' || c.kind === 'number') ? styles.right : undefined]}>
                {cellText(c.kind, totals[c.key] ?? null)}
              </Text>
            ))}
          </View>
        ) : null}

        <View style={styles.footer} fixed>
          <Text>
            Generated by {systemName} on {meta.generatedAt.split('T')[0]}
          </Text>
          <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}
