import { NextResponse } from 'next/server';
import ExcelJS from 'exceljs';
import { runReport } from '@/lib/reports/run';

/**
 * GET /api/reports/[slug]/export/excel?from&to&branch&officer&status
 * Server-side .xlsx: branded header, formatted numbers/dates,
 * frozen header row, auto-sized columns, totals row.
 */
export async function GET(req: Request, { params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  try {
    const { result } = await runReport(req, slug);
    const { meta, columns, rows, totals } = result;

    const wb = new ExcelJS.Workbook();
    wb.creator = meta.businessName;
    wb.created = new Date();
    const sheetName = meta.title.slice(0, 31) || 'Report';
    const ws = wb.addWorksheet(sheetName);

    const BRAND = 'FF00A6E0';
    const DARK = 'FF061633';

    // Title block
    ws.addRow([meta.businessName]);
    ws.addRow([meta.title]);
    ws.addRow([`Period: ${meta.from} to ${meta.to}`]);
    ws.addRow([`Generated by ${meta.generatedBy} on ${meta.generatedAt.split('T')[0]}`]);
    ws.addRow([]);
    for (let i = 1; i <= 4; i++) {
      const row = ws.getRow(i);
      row.font = { bold: i <= 2, size: i === 1 ? 14 : 11, color: { argb: DARK } };
    }

    // Header row
    const headerRow = ws.addRow(columns.map((c) => c.label));
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND } };
    const headerIndex = headerRow.number;

    // Data rows
    for (const r of rows) {
      ws.addRow(
        columns.map((c) => {
          const v = r[c.key];
          if (v === null || v === undefined || v === '') return '';
          if (c.kind === 'money' || c.kind === 'number') return Number(v);
          return String(v);
        }),
      );
    }

    // Totals row
    if (totals) {
      const tr = ws.addRow(
        columns.map((c) => {
          const v = totals[c.key];
          if (v === null || v === undefined || v === '') return '';
          if (c.kind === 'money' || c.kind === 'number') return Number(v);
          return String(v);
        }),
      );
      tr.font = { bold: true };
    }

    // Number formats + freeze + widths
    columns.forEach((c, i) => {
      const col = ws.getColumn(i + 1);
      if (c.kind === 'money') col.numFmt = '"K" #,##0.00';
      if (c.kind === 'date') col.numFmt = 'yyyy-mm-dd';
      let width = c.label.length + 2;
      for (let r = headerIndex + 1; r <= ws.rowCount; r++) {
        const v = ws.getRow(r).getCell(i + 1).value;
        const len = v === null || v === undefined ? 0 : String(v).length;
        if (len + 2 > width) width = len + 2;
      }
      col.width = Math.min(Math.max(width, 10), 42);
    });
    ws.views = [{ state: 'frozen', ySplit: headerIndex }];

    const buffer = await wb.xlsx.writeBuffer();
    const filename = `${slug}-${meta.from}-to-${meta.to}.xlsx`;
    return new NextResponse(buffer, {
      headers: {
        'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    });
  } catch (e) {
    const message = e instanceof Error ? e.message : 'Excel export failed';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
